"""
Run the equity backtest and the robustness backtest in parallel.

Both jobs read data/oos_predictions.parquet independently, so they run
concurrently as separate processes. Produces, in parallel:

  outputs/backtest_equity.jpg      (generated by backtest.py)
  outputs/backtest_robustness.jpg  (generated by backtest_robustness.py)

Usage:  python backtest_all.py
"""

import subprocess
import sys
import threading
import time
from pathlib import Path

HERE = Path(__file__).parent
PY = sys.executable


def _stream(name: str, proc: subprocess.Popen) -> None:
    """Forward a subprocess' output line by line, prefixed with the job name."""
    for line in proc.stdout:
        print(f"[{name:10s}] {line.rstrip()}", flush=True)


def main() -> None:
    jobs = [
        ("equity", HERE / "backtest.py"),
        ("robust", HERE / "backtest_robustness.py"),
    ]

    t0 = time.time()
    procs, threads = [], []
    for name, script in jobs:
        print(f"▶ launching {name} ({script.name}) ...", flush=True)
        proc = subprocess.Popen(
            [PY, str(script)], cwd=HERE,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1,
        )
        t = threading.Thread(target=_stream, args=(name, proc), daemon=True)
        t.start()
        procs.append((name, proc))
        threads.append(t)

    failed = []
    for (name, proc), t in zip(procs, threads):
        rc = proc.wait()
        t.join()
        status = "OK" if rc == 0 else f"FAILED (exit {rc})"
        print(f"■ {name}: {status}", flush=True)
        if rc != 0:
            failed.append(name)

    print(f"\nDone in {time.time() - t0:.0f}s")
    print("  → outputs/backtest_equity.jpg")
    print("  → outputs/backtest_robustness.jpg")
    if failed:
        sys.exit(f"FAILED: {', '.join(failed)}")


if __name__ == "__main__":
    main()
